import type { NextPage } from "next"
import Header from '../components/Header'
import Link from "next/link";
import Head from "next/head" 
import { useSession } from "next-auth/react"
import { signIn } from "next-auth/react";
import { signOut } from "next-auth/react";
import Secret from "../components/secret";
import { ChevronRightIcon, ChevronLeftIcon, DownloadIcon, ChatIcon, CameraIcon } from '@heroicons/react/solid'
import { BeakerIcon, PencilIcon ,AdjustmentsIcon, CodeIcon, CogIcon, LightningBoltIcon, DeviceMobileIcon, LockClosedIcon, CloudIcon  } from '@heroicons/react/outline'




const Home: NextPage = () => {

<Head>
  <title>Create T3 App</title>
  <meta name="description" content="Generated by create-t3-app" />
  <link rel="icon" href="/favicon.ico" />
</Head>    
    
const { data: session } = useSession()



if (session)  {

    return (
      <>
        <Header/> 
        <Secret/>
       </>
       )
  }
  return (
  <>
    <Header/> 
    <div className="lg:w-[80%] 2xl:w-[75%] mx-auto sm:border-r sm:border-l">
      <div className="bg-white w-full h-72 sm:h-96 lg:h-[350px] border-b relative overflow-hidden"> 
            <div className="bgElement z-[3] bg-gradient-to-l from-slate-200 to-white w-[900px] h-[900px] rounded-[500px] absolute -bottom-[50px] -right-[300px] hover:-right-[320px] transition-all duration-300"></div>
            <ChevronLeftIcon className="h-16 bottom-32 z-20 text-gray-300 absolute left-1 hover:-left-1 transition-all duration-300 cursor-pointer hover:text-gray-200"/>
            <ChevronRightIcon className="h-16 bottom-32 z-20 text-gray-300 absolute right-1 hover:-right-1 transition-all duration-300 cursor-pointer hover:text-gray-200"/>
            
            <div className="sm:ml-10 relative h-72 ml-[26px]">
              <p className=" sm:text-4xl font sm:max-w-xl z-10 relative font-extrabold tracking-tight text-gray-900 text-2xl max-w-xs sm:p-10 pt-6 p-10">Beautiful websites built on a modern technology stack.<br/>
              {/* <Link href="/about"><span className="text-blue-500 hover:text-blue-300 
              cursor-pointer font-extralight underline text-[16px] hover:ml-1 
              transition-all duration-300">Learn More</span></Link> */}
              </p>
              <h3 className=" absolute bottom-[24%] sm:bottom-[14%]
               sm:text-2xl text-lg italic text-slate-400 font-thin 
               opacity-60 ml-10 sm:ml-10 z-10 max-w-xs">Get in touch today for a free consultation.</h3>      
              <Link href={`/quote`}>
              <button className="bg-blue-400 z-20 hover:bg-blue-300 text-white 
              font-bold px-2 rounded inline-flex items-center absolute top-[80%] ml-10
              sm:top-[96%] sm:ml-10 h-10 sm:hover:top-[95%] hover:top-[79%]  hover:shadow transition-all duration-300">        
                <span>Get a Quote</span>
                <ChatIcon className="h-6 ml-2 " />
                </button>
              </Link>
            </div>
      </div>

      <div className="h-[900px]">

        <div className="grid grid-cols-2 x sm:grid-cols-4 pt-2 mx-4 bg-white text-center welcomeFeature">
          <span><h2>Beaker Service</h2><PencilIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
          <span><h2>Custom Code</h2><CodeIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
          <span><h2>Welcome Feature03</h2><CloudIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
          <span><h2>Welcome Feature04</h2><LockClosedIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
          <span><h2>Welcome Feature01</h2><DeviceMobileIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
          <span><h2>Welcome Feature02</h2><AdjustmentsIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
          <span><h2>Welcome Feature03</h2><CogIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
          <span><h2>Welcome Feature04</h2><LightningBoltIcon className="fIcon"/><div className="feature">Now we're talking baby! Check out this sweet content created really fast in Tailwind CSS.</div></span>
        </div>
            
        <div className="text-white">
          <ul>
            <li className="contentFeature">Content 1</li>
            <li className="contentFeature inverse">Content 2</li>
            <li className="contentFeature">Content 3</li>
          </ul>
        </div>
      </div>
    </div>
  </>          
  );
};



export default Home
